.TH "EquipmentManager" 3 "Sat Nov 14 2015" "A2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EquipmentManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEquipmentManager\fP ()"
.br
.ti -1c
.RI "\fBEquipment\fP * \fBcreateEquipment\fP (eqType type)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EquipmentManager::EquipmentManager ()\fC [inline]\fP"
\fBEquipmentManager\fP used to create and manage clones 

.SH "Author"
.PP 
Generated automatically by Doxygen for A2 from the source code\&.
