.TH "Equipment" 3 "Sat Nov 14 2015" "A2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Equipment \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBike\fP, and \fBTreadMill\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEquipment\fP ()"
.br
.ti -1c
.RI "virtual \fBEquipment\fP * \fBclone\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdisplay\fP () const  =0"
.br
.ti -1c
.RI "virtual void \fBsetName\fP (string)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Equipment::Equipment ()\fC [inline]\fP"
\fBEquipment\fP virtual class 

.SH "Author"
.PP 
Generated automatically by Doxygen for A2 from the source code\&.
