.TH "TreadMill" 3 "Sat Nov 14 2015" "A2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreadMill \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEquipment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTreadMill\fP (string name)"
.br
.ti -1c
.RI "\fBTreadMill\fP (const \fBTreadMill\fP &tread)"
.br
.ti -1c
.RI "\fBEquipment\fP * \fBclone\fP ()"
.br
.ti -1c
.RI "void \fBdisplay\fP () const "
.br
.ti -1c
.RI "void \fBsetName\fP (string name)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TreadMill::TreadMill (string name)\fC [inline]\fP"
Treadmill sub class of \fBEquipment\fP has a type and name 

.SH "Author"
.PP 
Generated automatically by Doxygen for A2 from the source code\&.
